# -----------------------------------
#   ██████╗██╗    ██╗██████╗
#  ██╔════╝██║    ██║██╔══██╗
#  ██║     ██║ █╗ ██║██████╔╝
#  ██║     ██║███╗██║██╔══██╗
#  ╚██████╗╚███╔███╔╝██║  ██║
#   ╚═════╝ ╚══╝╚══╝ ╚═╝  ╚═╝  (Dev)
# -----------------------------------
# available placeHolders. {
#   %cwr_ocom_mace_holder%
#   %cwr_ocom_heavy_core_drop_event%
# }
########################################
# NOTE : when unload the plugin it
#        saves its config automatically.
#        don't forget to unload plugin
#        before edit the config.
########################################
# One core one mace plugin config.
general-plugin-settings:
  how-long-a-holder-can-be-offline-in-minutes: 2160 # 1 day and 6 hours.
  how-long-he-should-be-stay-in-the-server-in-minutes: 90 # 1 hour and 30 minutes.
  how-long-he-can-remove-his-mace-from-his-inventory-in-minutes: 15

  can-a-mace-craft-using-auto-crafter: false
  remove-extra-mace-on-join: true
  remove-extra-mace-on-clicking-inventory: true
  remove-extra-mace-on-using: false # recommend to turn off this.
  debug_mod: false # this is only use for debug. always should be false.

# please don't change this details.
mace-holder-details:
  current-mace-holder: "null"
  is_heavy_core_dropped: false
  cancel-heavy-core-drop-event: false
  virtual-day-start: 0
  virtual-day-end: 0
  virtual-play-time: 0

TextStrings:
  prefix: "&7[&6CwR&7]&r"
  player-not-available: "n/a"

  mace-holder-massages:
    holder-remove-mace-from-inventory: "&7You are not able to remove mace from your inventory. if did not you get it back to your inventory. mace will be disappear."
    when-mace-holder-set: "&7Now you are the mace holder."
    when-mace-holder-null: "&7There are no longer a mace holder. find a heavy core as fast as possible."
    when-mace-holder-change-this-massage-to-old-holder: "&7You are loosing your mace."


