# -----------------------------------
#   ██████╗██╗    ██╗██████╗
#  ██╔════╝██║    ██║██╔══██╗
#  ██║     ██║ █╗ ██║██████╔╝
#  ██║     ██║███╗██║██╔══██╗
#  ╚██████╗╚███╔███╔╝██║  ██║
#   ╚═════╝ ╚══╝╚══╝ ╚═╝  ╚═╝  (Dev)
# -----------------------------------
# One core one mace plugin config.
general-plugin-settings:
  how-long-a-holder-can-be-offline-in-minutes: 2160 # 1 day and 6 hours.
  how-long-he-should-be-stay-in-the-server-in-minutes: 120 # 2 hours.
  how-long-he-can-remove-his-mace-from-his-inventory-in-minutes: 15

  # can-a-mace-craft-using-auto-crafter: false # deprecated.
  remove-extra-mace-on-join: true
  remove-extra-mace-on-clicking-inventory: false # recommend to turn off this.
  remove-extra-mace-on-using: false # recommend to turn off this.

# please don't change this details.
mace-holder-details:
  current-mace-holder: "null"
  is_heavy_core_dropped: false
  cancel-heavy-core-drop-event: false
  holder-last-logout: "n/a"
  virtual-day-start: "n/a"
  virtual-day-end: "n/a"
  virtual-day-next: "n/a"
  virtual-day-login: "n/a"
  virtual-day-logout: "n/a"

TextStrings:
  player-not-available: "n/a"

  mace-holder-warnings:
    prefix: "&4[WARN]&r "
    holder-remove-mace-from-inventory: "&7You are not able to remove mace from your inventory. if did not you get it back to your inventory. mace will be disappear."


